
language: python


python:
  - 3.4

sudo: false

virtualenv:

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - cp config.py.in config.py

script:
  - coverage run --source=urltheory,accesspredict -m unittest -v

after_success:
  - coveralls

